id: IFABEABE1
default_language: zh
source: https://www2.hf.uio.no/polyglotta/index.php?page=library&bid=2
initial_creation_type: input
imported: 2023-02-10 00:39:46.489054
last_modified: 2023-02-10 00:39:46.489206
source_metadata:
  title: Udānavarga
  language: zh
bases:
  D04D:
    base_file: D04D.txt
    order: 1
copyright:
  status: Unknown
  notice: ''
